AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sample ruby application'

Resources:
  TranscodeVideoFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: ruby2.5

Outputs:
  TranscodeVideoFunc:
    Description: Hello Ruby Record Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TranscodeVideoFunc
      - Arn
