AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Transcode a video uploaded to S3

Resources:
  TranscodeVideoFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Role: arn:aws:iam::958135493453:role/book-lambda-s3-execution-role

  TriggerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt 
        - TranscodeVideoFunc
        - Arn
      Principal: s3.amazonaws.com
      SourceArn: !Join 
                  - ""
                  - - 'arn:aws:s3:::'
                    - book-serverless-video-upload

Outputs:
  TranscodeVideoFunc:
    Description: Video transcoder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TranscodeVideoFunc
      - Arn
